version: '3'
services:
  nginx-web:
    image: nginx:stable-alpine
    container_name: ${CONTAINER_NAME_WEB}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS}:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE}
        max-file: ${NGINX_WEB_LOG_MAX_FILE}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${CONTAINER_NAME_WEB} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${CONTAINER_NAME_GEN}
    restart: always
    environment:
      SSL_POLICY: ${SSL_POLICY}
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE}
        max-file: ${NGINX_GEN_LOG_MAX_FILE}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: ${CONTAINER_NAME_LETSENCRYPT}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${CONTAINER_NAME_GEN}
      NGINX_PROXY_CONTAINER: ${CONTAINER_NAME_WEB}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE}

networks:
  default:
    external:
      name: ${NETWORK}
